/* Stammtisch Annals private-intake helpers.
 * This file contains NO email account, external API, publisher or network calls.
 * Intended to be copied into a dedicated Google Apps Script project together
 * with Code.gs. Any data generated by these helpers is PRIVATE staging only.
 */
var AnnalsPilot = (function () {
  'use strict';

  var SCHEMA_VERSION = 1;
  var MAX_BODY_CHARS = 16000;
  var MAX_ATTACHMENTS = 6;
  var MAX_ATTACHMENT_BYTES = 8 * 1024 * 1024;
  var MAX_TOTAL_BYTES = 20 * 1024 * 1024;

  var EXTENSIONS = Object.freeze({
    'image/jpeg': '.jpg',
    'image/png': '.png',
    'image/webp': '.webp',
    'image/heic': '.heic',
    'image/heif': '.heif',
    'application/pdf': '.pdf',
    'text/plain': '.txt'
  });

  function senderAddress(raw) {
    if (typeof raw !== 'string' || raw.length > 320) return null;
    var trimmed = raw.trim();
    var angle = trimmed.match(/<([^<>]+)>\s*$/);
    var address = (angle ? angle[1] : trimmed).trim().toLowerCase();
    // This is only a triage check, NOT proof of authenticated email.
    if (!/^[a-z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?\.[a-z]{2,}$/.test(address)) return null;
    if (address.indexOf('..') !== -1) return null;
    return address;
  }

  function allowedSenders(csv) {
    if (typeof csv !== 'string') return [];
    var values = csv.split(',').map(function (s) { return senderAddress(s); });
    if (values.some(function (v) { return !v; })) return [];
    return Array.from(new Set(values));
  }

  function classify(subject, body) {
    var text = String(subject || '') + ' ' + String(body || '').slice(0, 2000);
    if (/\b(cocktail|syrup|recipe|mocktail|shrub|garnish|negroni|martini|mixed drinks?)\b/i.test(text)) return 'cocktail';
    if (/\b(quote|quotation|someone said|overheard|wisdom)\b/i.test(text)) return 'quotation';
    if (/\b(annual assembly|annual retreat|cottage weekend)\b/i.test(text)) return 'assembly';
    if (/\b(monthly stam(m)?tisch|third friday|monthly meeting)\b/i.test(text)) return 'monthly_gathering';
    if (/\b(annals|history|archive|old photo|remember when)\b/i.test(text)) return 'club_history';
    return 'uncategorised';
  }

  function attachmentPolicy(mime, bytes) {
    var normalized = String(mime || '').toLowerCase().split(';')[0].trim();
    if (!Number.isSafeInteger(bytes) || bytes < 0 || bytes > MAX_ATTACHMENT_BYTES) {
      return { accepted: false, reason: 'invalid_or_large_attachment', extension: null };
    }
    if (!Object.prototype.hasOwnProperty.call(EXTENSIONS, normalized)) {
      return { accepted: false, reason: 'unsupported_attachment_type', extension: null };
    }
    var conversionNeeded = normalized === 'image/heic' || normalized === 'image/heif';
    return {
      accepted: true,
      reason: conversionNeeded ? 'private_conversion_needed' : 'private_staging_only',
      extension: EXTENSIONS[normalized],
      conversionNeeded: conversionNeeded
    };
  }

  function planAttachments(attachments) {
    if (!Array.isArray(attachments)) return { held: true, reason: 'attachments_not_an_array', items: [] };
    if (attachments.length > MAX_ATTACHMENTS) return { held: true, reason: 'too_many_attachments', items: [] };
    var total = 0;
    var held = false;
    var items = attachments.map(function (attachment, index) {
      var size = attachment && attachment.size;
      var policy = attachmentPolicy(attachment && attachment.mime, size);
      if (Number.isSafeInteger(size) && size >= 0) total += size;
      if (!policy.accepted || policy.conversionNeeded) held = true;
      return {
        index: index + 1,
        mime: typeof attachment.mime === 'string' ? attachment.mime.slice(0, 100) : '',
        size: size,
        storageName: policy.extension ? ('attachment-' + String(index + 1).padStart(2, '0') + policy.extension) : null,
        accepted: policy.accepted,
        requiresConversion: !!policy.conversionNeeded,
        reason: policy.reason
      };
    });
    if (total > MAX_TOTAL_BYTES) return { held: true, reason: 'total_attachments_too_large', items: items };
    return { held: held, reason: held ? 'attachment_review_required' : 'private_staging_only', items: items };
  }

  function privateProposal(params) {
    if (!params || typeof params !== 'object') throw new TypeError('Expected private message data');
    var id = String(params.sourceId || '');
    if (!/^[a-f0-9]{64}$/.test(id)) throw new Error('Source ID must be SHA-256 hex digest');
    var subject = String(params.subject || '').slice(0, 240);
    var body = String(params.body || '');
    var from = senderAddress(params.from);
    if (!from) throw new Error('No usable sender address');
    var bodyTruncated = body.length > MAX_BODY_CHARS;
    var safeBody = body.slice(0, MAX_BODY_CHARS);
    var plan = planAttachments(params.attachments || []);
    return {
      schemaVersion: SCHEMA_VERSION,
      sourceId: id,
      state: 'private_review_required',
      publicationApproved: false,
      publishable: false,
      categorisation: classify(subject, safeBody),
      categorisationIsSuggestion: true,
      source: {
        sender: from, // PRIVATE, never committed to public GitHub.
        subject: subject,
        receivedAt: params.receivedAt || null,
        excerpt: safeBody,
        excerptTruncated: bodyTruncated
      },
      attachmentManifest: plan,
      requiresClarification: bodyTruncated || plan.held,
      quoteMustStayVerbatim: true,
      eventDateConfirmed: false,
      creditedCreatorConfirmed: false,
      photoConsentConfirmed: false,
      aiDraftAvailable: false,
      note: 'No automatic publication. Content is unverified private evidence.'
    };
  }

  function publicationBlocked(/* proposal */) {
    // Phase 0/1 must never publish. A separately reviewed exact-content,
    // authenticated approval workflow is required before any new publisher.
    return true;
  }

  return Object.freeze({
    SCHEMA_VERSION: SCHEMA_VERSION,
    MAX_BODY_CHARS: MAX_BODY_CHARS,
    MAX_ATTACHMENTS: MAX_ATTACHMENTS,
    MAX_ATTACHMENT_BYTES: MAX_ATTACHMENT_BYTES,
    MAX_TOTAL_BYTES: MAX_TOTAL_BYTES,
    senderAddress: senderAddress,
    allowedSenders: allowedSenders,
    classify: classify,
    attachmentPolicy: attachmentPolicy,
    planAttachments: planAttachments,
    privateProposal: privateProposal,
    publicationBlocked: publicationBlocked
  });
})();

if (typeof module !== 'undefined' && module.exports) {
  module.exports = AnnalsPilot;
}
